# This is a basic workflow to help you get started with Actions

name: StarRail

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]
  #schedule:
    #- cron: '0 21  * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      LANG: ja-jp
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Japan"
          timezoneMacos: "Asia/Japan"
          timezoneWindows: "Japan Standard Time"

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
        
      - name: Setup Python
        uses: actions/setup-python@v4.6.0
        with:
           python-version: '3.11' 
        
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: Install requirement
        run: |
         python -m pip install --upgrade pip
         pip install onepush
         pip install hoyo-daily-logins-helper
      - name: daily
        run: HOYO_LANGUAGE=ja-jp hoyo-daily-logins-helper --cookie="${{ secrets.HOYO_COOKIE }}" --starrail  &> output.log

      - name: send
        env:
          WEBHOOK: ${{ secrets.WEBHOOK }}

        run: |
         python send.py
         
      - name: upload
        run: |
          month=$(date +'%Y/%m')
          day=$(date +'%Y/%m/%d')
          mkdir -p "$month"
          mv output.log "$day.log"
          # Configure git
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          # Commit and push the log file
          git add "$day.log"
          git commit -m "$day.log"
          git push
     
          
